from enum import Enum
'''
All the data that the device can provide
'''

class InstantaneousParameters(Enum):
    voltage = 'VOLTAGE'
    current = 'CURRENT'
    active_power = 'ACTIVE_POWER'
    apparent_power = 'APPARENT_POWER'
    reactive_power = 'REACTIVE_POWER'
    frequency = 'FREQUENCY'
    power_factor = 'POWER_FACTOR'

class PowerParameters(Enum):
    positive_total_active_energy = 'POSITIVE_TOTAL_ACTIVE_ENERGY'
    t1_total_forward_active_energy = 'T1_TOTAL_FORWARD_ACTIVE_ENERGY'
    t2_total_forward_active_energy = 'T2_TOTAL_FORWARD_ACTIVE_ENERGY'
    t3_total_forward_active_energy = 'T3_TOTAL_FORWARD_ACTIVE_ENERGY'
    t4_total_forward_active_energy = 'T4_TOTAL_FORWARD_ACTIVE_ENERGY'
    total_reverse_active_energy = 'TOTAL_REVERSE_ACTIVE_ENERGY'
    t1_total_reverse_active_energy = 'T1_TOTAL_REVERSE_ACTIVE_ENERGY'
    t2_total_reverse_active_energy = 'T2_TOTAL_REVERSE_ACTIVE_ENERGY'
    t3_total_reverse_active_energy = 'T3_TOTAL_REVERSE_ACTIVE_ENERGY'
    t4_total_reverse_active_energy = 'T4_TOTAL_REVERSE_ACTIVE_ENERGY'
    active_total_power = 'ACTIVE_TOTAL_POWER'
    t1_total_active_energy = 'T1_TOTAL_ACTIVE_ENERGY'
    t2_total_active_energy = 'T2_TOTAL_ACTIVE_ENERGY'
    t3_total_active_energy = 'T3_TOTAL_ACTIVE_ENERGY'
    t4_total_active_energy = 'T4_TOTAL_ACTIVE_ENERGY'
    total_forward_reactive_energy = 'TOTAL_FORWARD_REACTIVE_ENERGY'
    t1_total_forward_reactive_energy = 'T1_TOTAL_FORWARD_REACTIVE_ENERGY'
    t2_total_forward_reactive_energy = 'T2_TOTAL_FORWARD_REACTIVE_ENERGY'
    t3_total_forward_reactive_energy = 'T3_TOTAL_FORWARD_REACTIVE_ENERGY'
    t4_total_forward_reactive_energy = 'T4_TOTAL_FORWARD_REACTIVE_ENERGY'
    total_reverse_reactive_energy = 'TOTAL_REVERSE_REACTIVE_ENERGY'
    t1_total_reverse_reactive_energy = 'T1_TOTAL_REVERSE_REACTIVE_ENERGY'
    t2_total_reverse_reactive_energy = 'T2_TOTAL_REVERSE_REACTIVE_ENERGY'
    t3_total_reverse_reactive_energy = 'T3_TOTAL_REVERSE_REACTIVE_ENERGY'
    t4_total_reverse_reactive_energy = 'T4_TOTAL_REVERSE_REACTIVE_ENERGY'
    total_reactive_energy = 'TOTAL_REACTIVE_ENERGY'
    t1_total_reactive_energy = 'T1_TOTAL_REACTIVE_ENERGY'
    t2_total_reactive_energy = 'T2_TOTAL_REACTIVE_ENERGY'
    t3_total_reactive_energy = 'T3_TOTAL_REACTIVE_ENERGY'
    t4_total_reactive_energy = 'T4_TOTAL_REACTIVE_ENERGY'
    total_reactive_energy_first_quadrant = 'TOTAL_REACTIVE_ENERGY_FIRST_QUADRANT'
    t1_first_quadrant_total_reactive_energy = 'T1_FIRST_QUADRANT_TOTAL_REACTIVE_ENERGY'
    t2_first_quadrant_total_reactive_energy = 'T2_FIRST_QUADRANT_TOTAL_REACTIVE_ENERGY'
    t3_first_quadrant_total_reactive_energy = 'T3_FIRST_QUADRANT_TOTAL_REACTIVE_ENERGY'
    t4_first_quadrant_total_reactive_energy = 'T4_FIRST_QUADRANT_TOTAL_REACTIVE_ENERGY'
    total_reactive_energy_second_quadrant = 'TOTAL_REACTIVE_ENERGY_SECOND_QUADRANT'
    t1_second_quadrant_total_reactive_energy = 'T1_SECOND_QUADRANT_TOTAL_REACTIVE_ENERGY'
    t2_second_quadrant_total_reactive_energy = 'T2_SECOND_QUADRANT_TOTAL_REACTIVE_ENERGY'
    t3_second_quadrant_total_reactive_energy = 'T3_SECOND_QUADRANT_TOTAL_REACTIVE_ENERGY'
    t4_second_quadrant_total_reactive_energy = 'T4_SECOND_QUADRANT_TOTAL_REACTIVE_ENERGY'

class MeterParameters(Enum):
    item = 'ITEM'
    modbus_id = 'MODBUS_ID'
    software_version_number = 'SOFTWARE_VERSION_NUMBER'
    hardware_version_number = 'HARDWARE_VERSION_NUMBER'
    firmware_checksum = 'FIRMWARE_CHECKSUM'
    time = 'TIME'
    rotation_time = 'ROTATION_TIME'
    baud_rate_485 = 'BAUD_RATE_485'
    check_digit_485 = 'CHECK_DIGIT_485'
    stop_bit_485 = 'STOP_BIT_485'
    combined_code = 'COMBINED_CODE'
    demand_mode = 'DEMAND_MODE'
    demand_cycle = 'DEMAND_CYCLE'
    automatic_rotation_content = 'AUTOMATIC_ROTATION_CONTENT'
    lcd_button_display_setting_password = 'LCD_BUTTON_DISPLAY_SETTING_PASSWORD'
    meter_running_time = 'METER_RUNNING_TIME'
    set_timing_current_value = 'SET_TIMING_CURRENT_VALUE'
    meter_running_status_word_1 = 'METER_RUNNING_STATUS_WORD_1'
    meter_running_status_word_2 = 'METER_RUNNING_STATUS_WORD_2'
    meter_running_status_word_3 = 'METER_RUNNING_STATUS_WORD_3'
    meter_running_status_word_4 = 'METER_RUNNING_STATUS_WORD_4'
    meter_running_status_word_5 = 'METER_RUNNING_STATUS_WORD_5'
    meter_running_status_word_6 = 'METER_RUNNING_STATUS_WORD_6'
    meter_running_status_word_7 = 'METER_RUNNING_STATUS_WORD_7'
    meter_running_status_word_block = 'METER_RUNNING_STATUS_WORD_BLOCK'
    clear_electricity = 'CLEAR_ELECTRICITY'
    clear_max_demand = 'CLEAR_MAX_DEMAND'

class TariffParameters(Enum):
    timetable_1 = 'TIMETABLE_1'
    timetable_2 = 'TIMETABLE_2'
    timetable_3 = 'TIMETABLE_3'
    timetable_4 = 'TIMETABLE_4'
    timetable_5 = 'TIMETABLE_5'
    timetable_6 = 'TIMETABLE_6'
    timetable_7 = 'TIMETABLE_7'
    timetable_8 = 'TIMETABLE_8'
    time_zone_table = 'TIME_ZONE_TABLE'
    holiday_table = 'HOLIDAY_TABLE'
